DROP TABLE IF EXISTS article_categorie CASCADE;
DROP TABLE IF EXISTS article_auteur CASCADE;
DROP TABLE IF EXISTS images CASCADE;
DROP TABLE IF EXISTS sources CASCADE;
DROP TABLE IF EXISTS articles CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS auteurs CASCADE;
DROP TABLE IF EXISTS utilisateurs CASCADE;
